services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Demo_Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Demo_Password123!
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped

volumes:
  sqldata: