// <auto-generated />
using System;
using Inventario.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Api.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    partial class InventarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Api.Stock", b =>
                {
                    b.Property<Guid>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Disponible")
                        .HasColumnType("int");

                    b.Property<int>("Reservado")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.ToTable("Stocks", (string)null);

                    b.HasData(
                        new
                        {
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Disponible = 10,
                            Reservado = 0
                        },
                        new
                        {
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Disponible = 3,
                            Reservado = 0
                        },
                        new
                        {
                            ProductoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Disponible = 0,
                            Reservado = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
